// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADvJPbAiNsBUU5RGjo9x9QVEefUjH3lxs',
    appId: '1:1017903060333:web:1aace5fc2dbf19ae8bb664',
    messagingSenderId: '1017903060333',
    projectId: 'fintech-906b0',
    authDomain: 'fintech-906b0.firebaseapp.com',
    storageBucket: 'fintech-906b0.firebasestorage.app',
    measurementId: 'G-DN717DS776',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOUjR7bbxN0h2Ndz6eyIHTymZmRxAYE7w',
    appId: '1:1017903060333:android:a2600a19684b804f8bb664',
    messagingSenderId: '1017903060333',
    projectId: 'fintech-906b0',
    storageBucket: 'fintech-906b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPsBHAaIoxq-OXM5q5LPP6Il2CPHd-mlE',
    appId: '1:1017903060333:ios:40090ad6286ef4978bb664',
    messagingSenderId: '1017903060333',
    projectId: 'fintech-906b0',
    storageBucket: 'fintech-906b0.firebasestorage.app',
    iosBundleId: 'com.example.fintech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPsBHAaIoxq-OXM5q5LPP6Il2CPHd-mlE',
    appId: '1:1017903060333:ios:40090ad6286ef4978bb664',
    messagingSenderId: '1017903060333',
    projectId: 'fintech-906b0',
    storageBucket: 'fintech-906b0.firebasestorage.app',
    iosBundleId: 'com.example.fintech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADvJPbAiNsBUU5RGjo9x9QVEefUjH3lxs',
    appId: '1:1017903060333:web:a5908cb6e13e0bfe8bb664',
    messagingSenderId: '1017903060333',
    projectId: 'fintech-906b0',
    authDomain: 'fintech-906b0.firebaseapp.com',
    storageBucket: 'fintech-906b0.firebasestorage.app',
    measurementId: 'G-Z2WCG56WME',
  );
}
